apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-fase-4-payments-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-fase-4-payments-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
