apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-fase-4-payments-nodeport
spec:
  type: NodePort
  selector:
    app: tech-challenge-fase-4-payments-deployment
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007
