basePath: /api/v1
definitions:
  controllers.CreatePaymentRequest:
    properties:
      amount:
        type: number
    type: object
  controllers.ProcessPaymentRequest:
    properties:
      payment_status:
        type: string
    type: object
  dtos.MethodType:
    enum:
    - PIX
    - CREDIT_CARD
    type: string
    x-enum-varnames:
    - PIX
    - CREDIT_CARD
  dtos.PaymentRequestDTO:
    properties:
      amount:
        type: number
      method:
        $ref: '#/definitions/dtos.MethodType'
      orderId:
        type: string
      paymentLink:
        type: string
    type: object
  dtos.PaymentStatusDTO:
    properties:
      order_id:
        type: string
      payment_status:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /payment/{order_id}:
    get:
      consumes:
      - application/json
      description: get payment status by order_id
      parameters:
      - description: Get Payment Status
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.PaymentStatusDTO'
        "400":
          description: when bad request
          schema:
            type: string
        "406":
          description: when invalid params or invalid object
          schema:
            type: string
      summary: Get a payment status
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: request a new payment by order_id
      parameters:
      - description: Get Payment Status
        in: path
        name: order_id
        required: true
        type: string
      - description: Payment Request
        in: body
        name: payment_request
        required: true
        schema:
          $ref: '#/definitions/controllers.CreatePaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.PaymentRequestDTO'
        "400":
          description: when bad request
          schema:
            type: string
        "406":
          description: when invalid params or invalid object
          schema:
            type: string
      summary: Request new payment
      tags:
      - orders
  /payment/{order_id}/process:
    post:
      consumes:
      - application/json
      description: process the payment for an order
      parameters:
      - description: Process Payment Request
        in: path
        name: order_id
        required: true
        type: string
      - description: Process Payment Request
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/controllers.ProcessPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: when bad request
          schema:
            type: string
        "406":
          description: when invalid params or invalid object
          schema:
            type: string
      summary: Process order payment
      tags:
      - orders
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
